// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fumntoewegtmnbvbtuvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bW50b2V3ZWd0bW5idmJ0dXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzM1NTIsImV4cCI6MjA3NDMwOTU1Mn0.8Zp6jrai0ZWjiof1P17DGHj63nhRHVlEwfs1JdYX8p4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});